################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
DSP2833x_ADC_cal.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/source/DSP2833x_ADC_cal.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_ADC_cal.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_CodeStartBranch.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/source/DSP2833x_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_CodeStartBranch.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_CpuTimers.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/source/DSP2833x_CpuTimers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_CpuTimers.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_DefaultIsr.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/source/DSP2833x_DefaultIsr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_DefaultIsr.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_GlobalVariableDefs.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/source/DSP2833x_GlobalVariableDefs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_GlobalVariableDefs.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_PieCtrl.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/source/DSP2833x_PieCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_PieCtrl.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_PieVect.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/source/DSP2833x_PieVect.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_PieVect.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Sci.obj: ../DSP2833x_Sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_Sci.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_SysCtrl.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/source/DSP2833x_SysCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_SysCtrl.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_usDelay.obj: C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/source/DSP2833x_usDelay.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="DSP2833x_usDelay.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Example_2833xLEDBlink.obj: ../Example_2833xLEDBlink.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="Example_2833xLEDBlink.d" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


