################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
QP_qf/qa_defer.obj: ../QP_qf/qa_defer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qa_defer.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qa_fifo.obj: ../QP_qf/qa_fifo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qa_fifo.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qa_get_.obj: ../QP_qf/qa_get_.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qa_get_.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qa_lifo.obj: ../QP_qf/qa_lifo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qa_lifo.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qa_sub.obj: ../QP_qf/qa_sub.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qa_sub.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qa_usub.obj: ../QP_qf/qa_usub.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qa_usub.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qa_usuba.obj: ../QP_qf/qa_usuba.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qa_usuba.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qeq_fifo.obj: ../QP_qf/qeq_fifo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qeq_fifo.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qeq_get.obj: ../QP_qf/qeq_get.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qeq_get.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qeq_init.obj: ../QP_qf/qeq_init.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qeq_init.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qeq_lifo.obj: ../QP_qf/qeq_lifo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qeq_lifo.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_act.obj: ../QP_qf/qf_act.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_act.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_gc.obj: ../QP_qf/qf_gc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_gc.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_log2.obj: ../QP_qf/qf_log2.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_log2.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_new.obj: ../QP_qf/qf_new.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_new.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_pool.obj: ../QP_qf/qf_pool.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_pool.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_psini.obj: ../QP_qf/qf_psini.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_psini.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_pspub.obj: ../QP_qf/qf_pspub.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_pspub.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_pwr2.obj: ../QP_qf/qf_pwr2.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_pwr2.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qf_tick.obj: ../QP_qf/qf_tick.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qf_tick.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qmp_get.obj: ../QP_qf/qmp_get.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qmp_get.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qmp_init.obj: ../QP_qf/qmp_init.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qmp_init.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qmp_put.obj: ../QP_qf/qmp_put.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qmp_put.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qte_arm.obj: ../QP_qf/qte_arm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qte_arm.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qte_ctor.obj: ../QP_qf/qte_ctor.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qte_ctor.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qte_ctr.obj: ../QP_qf/qte_ctr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qte_ctr.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qte_darm.obj: ../QP_qf/qte_darm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qte_darm.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qte_rarm.obj: ../QP_qf/qte_rarm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qte_rarm.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

QP_qf/qvanilla.obj: ../QP_qf/qvanilla.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="C:/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Console" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/Blinky" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_include" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_port" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qep" --include_path="C:/Users/martisek/Desktop/TI_projects/Example_2833xLEDBlink/QP_qf" --include_path="/packages/ti/xdais" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_headers/include" --include_path="C:/ti/controlSUITE/device_support/f2833x/v140/DSP2833x_common/include" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v15c/include" --include_path="C:/ti/controlSUITE/libs/math/FPUfastRTS/V100/include" -g --define="_DEBUG" --define="LARGE_MODEL" --quiet --diag_suppress=10063 --diag_warning=225 --verbose_diagnostics --issue_remarks --output_all_syms --cdebug_asm_data --preproc_with_compile --preproc_dependency="QP_qf/qvanilla.d" --obj_directory="QP_qf" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


